# Generated by Django 3.2.9 on 2021-11-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211118_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
